// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boikaxyzhuqhbxqvppbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvaWtheHl6aHVxaGJ4cXZwcGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MTU3ODksImV4cCI6MjA3NTA5MTc4OX0.-yER5ypnnG7ULVyWvpKTB95PL6E4fOmkSr1RzKu_Wzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});